server:
  port: 8000
  context-path: /api

management:
  server:
    servlet:
      context-path: /actuator

spring:
  datasource:
    url: jdbc:mysql://localhost/start-wars?useSSL=false
    username: root
    password: '1234'
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 500
        rewriteBatchedStatements: true
        idle-timeout: 10000
  jpa:
    generate-ddl: true
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

app:
  aplication-name: api-start-wars
  api:
    start-wars:
      uri: https://swapi.co/api/
