server:
  port: 8000

spring:

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 500
        rewriteBatchedStatements: true
        idle-timeout: 10000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show_sql: true
    hibernate:
      ddl-auto: update